# Generated by Django 3.0 on 2019-12-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=20)),
                ('album', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=10)),
                ('track_number', models.IntegerField()),
                ('order', models.IntegerField()),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albumranker.Ranking')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('ranking', 'order')},
            },
        ),
    ]
